# This file was generated by Bundix.
# Don't edit it manually.

{
  cocoapods = {
    dependencies = ["activesupport" "addressable" "algoliasearch" "atomos" "claide" "cocoapods-core" "cocoapods-deintegrate" "cocoapods-downloader" "cocoapods-plugins" "cocoapods-search" "cocoapods-trunk" "cocoapods-try" "colored2" "escape" "fourflusher" "gh_inspector" "molinillo" "nap" "ruby-macho" "xcodeproj"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
      type = "gem";
    };
    version = "1.16.2";
  };
  fastlane = {
    dependencies = ["CFPropertyList" "addressable" "artifactory" "aws-sdk-s3" "babosa" "bundler" "colored" "commander" "dotenv" "emoji_regex" "excon" "faraday" "faraday-cookie_jar" "faraday_middleware" "fastimage" "fastlane-sirp" "gh_inspector" "google-apis-androidpublisher_v3" "google-apis-playcustomapp_v1" "google-cloud-env" "google-cloud-storage" "highline" "http-cookie" "json" "jwt" "mini_magick" "multipart-post" "naturally" "optparse" "plist" "rubyzip" "security" "simctl" "terminal-notifier" "terminal-table" "tty-screen" "tty-spinner" "word_wrap" "xcodeproj" "xcpretty" "xcpretty-travis-formatter"];
    groups = ["default"];
    platforms = [];
    source = {
      remotes = ["https://rubygems.org"];
      sha256 = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
      type = "gem";
    };
    version = "2.228.0";
  };
}
